theme: jekyll-theme-minimal
title: Gary Benattar
description: Former Co-Founder ZenGo, Senior Software Development Manager AWS, Sports enthusiast (Climbing, Brazilian jiu-jitsu, Boxing...)
show_downloads: false
logo: ./assets/profile-bw.png
