theme: jekyll-theme-minimal
title: Gary Benattar
description: Former Co-Founder ZenGo, Principal Software Engineer Toluna (fmr Amazon), Sports enthusiast (Climbing, Brazilian jiu-jitsu, Boxing...)
show_downloads: false
logo: ./assets/profile.png